mysql-username: root
mysql-password: Root@123

eureka:
  instance:
    hostname: config-server
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
            defaultZone: http://service-registry:8761/eureka/
