#COMMON
mysql-username: root
mysql-password: Root@123

#CONFIG-SERVER
config-server-port: 8082

#API-GATEWAY
gateway-server-port: 8080

#DMA-SERVICE
dma-server-port: 8083
dma-database: induct-dma

#PRODUCT-SERVICE
product-server-port: 8084
product-database: induct-product
